### ISSUE TITLE
CS:S Popup exception

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#21]
When using this code in Counterstrike Source:

```
event player_say
{
    es popup create test_popup
    es popup addline test_popup "This is a test"
    es popup addline test_popup "->1. Test"
    es popup addline test_popup "->2. Test"
    es popup addline test_popup "0. Exit"
    es popup send test_popup event_var(userid)
}
```
 
The menu shows ingame but I get this exception:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\es_emulator\logic.py", line 318, in on_tick
    es.addons.tick()
  File "..\addons\source-python\plugins\es_emulator\eventscripts\es.py", line 291, in tick
    x()
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\gamethread.py", line 169, in tick
    _executenode(first)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\gamethread.py", line 151, in _executenode
    function(*a, **kw)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 1550, in refreshPopup
    return self.updatePopup(p)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 1542, in updatePopup
    self.handleQueue()
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 1452, in handleQueue
    es.event("setint","popup_display","userid",self.userid)
  File "..\addons\source-python\plugins\es_emulator\helpers.py", line 206, in wrapper
    return func(c)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\es_C.py", line 907, in event
    _current_event.set_int(value_name, atoi(value))

AttributeError: 'NoneType' object has no attribute 'set_int'
```

If I try to close the menu, it just reappears when the repeat happens with the exception.

Edit:

If I use es_load popup in CS:GO I get this error in the console:

`es_load popup
CGameEventManager::AddListener: event 'popup_display' unknown.
CGameEventManager::AddListener: event 'popup_select' unknown.
[EventScripts] Loaded popup`

Mabye that might be the case in CS:S too and the cause for the NoneType in the exception above

**Comment by Ayuto** [comment]
I'm not able to reproduce the exception. Are there any special steps I need to do?

**Comment by kamikazekuh** [comment]
Using the newest SP version and the newest Emulator version without any other plugins beeing loaded I still get the error above in CS:S.

In CS:GO I get this exception now:

`[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\es_emulator\logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "..\addons\source-python\plugins\es_emulator\eventscripts\popup\popup.py", line 169, in consolecmd
    p.send(playerlib.getUseridList(users),prio)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 256, in send
    user.handleQueue()
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 1419, in handleQueue
    menudisplay = qpopup.checkCache(self.userid)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 635, in checkCache
    self.recache(userid)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 543, in recache
    self.cache[userlang] = self.i_recache(userlang)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\popuplib.py", line 602, in i_recache
    menuitems[choice]['command'])
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\msglib.py", line 39, in addOption
    self.kv[names] = keyvalues.KeyValues(name=names)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\_libs\python\keyvalues.py", line 147, in __setitem__
    es.keyprecursivekeycopy(x, value._id_)
  File "..\addons\source-python\plugins\es_emulator\eventscripts\es_C.py", line 2034, in keyprecursivekeycopy
    _make_keyvalues(key_ptr).recursive_copy(

AttributeError: 'KeyValues' object has no attribute 'recursive_copy'`

**Comment by Ayuto** [comment]
``recursive_copy`` has been added a while ago. The following messages just have been fixed:
```
CGameEventManager::AddListener: event 'popup_display' unknown.
CGameEventManager::AddListener: event 'popup_select' unknown.
```

https://github.com/Ayuto/EventScripts-Emulator/commit/8a16ba7fe5a71c813159005be49294c18b5fa671
