### ISSUE TITLE
KeyError 'settings' regarding weaponlib update

### ISSUE THREAD

**Issue by NosferatuJoe** [Ayuto/EventScripts-Emulator#48]
Error: 
[SP] Loading plugin 'wcs'...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 207, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\wcs\wcs.py", line 196, in <module>
    from .core.helpers.esc.monkeypatch import cmd_manager  # Just to load it
  File "..\addons\source-python\plugins\wcs\core\helpers\esc\monkeypatch.py", line 28, in <module>
    from .commands import _format_message
  File "..\addons\source-python\plugins\wcs\core\helpers\esc\commands.py", line 91, in <module>
    from playerlib import Player as _PLPlayer
  File "..\addons\source-python\plugins\es_emulator\eventscripts_libs\python\playerlib.py", line 5, in <module>
    import weaponlib
  File "..\addons\source-python\plugins\es_emulator\eventscripts_libs\python\weaponlib__init.py", line 230, in <module>
    currentgame = getGameWeapons(es.getGameName()) or NoWeaponManager(es.getGameName())
  File "..\addons\source-python\plugins\es_emulator\eventscripts_libs\python\weaponlib\init.py", line 212, in getGameWeapons
    settings = ini['settings']
  File "..\addons\source-python\packages\site-packages\configobj.py", line 554, in getitem
    val = dict.getitem__(self, key)

KeyError: 'settings'

[SP] Plugin 'wcs' was unable to be loaded.

This error appears after latest update.

Temp solution provided by @ThaPwned: 
if you're still having that issue, you can modify the addons/source-python/plugins/es_emulator/eventscripts/_libs/python/weaponlib/csgo.ini file by changing [properties] to [settings] .

Thanks in advance!

**Comment by Ayuto** [comment]
Thanks! I forgot to change that name.

**Comment by NosferatuJoe** [comment]
Thank you for addressing the issue!
