### ISSUE TITLE
Exception list

### ISSUE THREAD

**Issue by NosferatuJoe** [Ayuto/EventScripts-Emulator#54]
```
2021-02-09 14:08:18 - sp	-	DEBUG	Setting up the "sp" command...
2021-02-09 14:08:18 - sp	-	WARNING	
[SP] Encountered a Warning:
  File '../addons/source-python/packages/site-packages/mutagen/id3/_specs.py', line 666: DeprecationWarning
    invalid escape sequence \s

2021-02-09 14:08:18 - sp	-	DEBUG	Hooking function: type=PRE, addr=4093241264, conv=CDECL, args=(_memory.DataType.POINTER, _memory.DataType.INT, _memory.DataType.INT, _memory.DataType.BOOL), rtype=BOOL, callback=<function _pre_set_client_listening at 0xedd13fa4>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__<<function _on_client_disconnect at 0xedc3cdf4>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	Hooking function: type=PRE, addr=4092131616, conv=CDECL, args=(_memory.DataType.POINTER, _memory.DataType.POINTER, _memory.DataType.STRING), rtype=VOID, callback=<function _pre_client_command at 0xedaaedf4>
2021-02-09 14:08:18 - sp	-	DEBUG	OnLevelEnd.__init__<<function _level_end at 0xedab1fa4>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnLevelEnd.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	Setting up auth...
2021-02-09 14:08:18 - sp	-	DEBUG	Setting up user settings...
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__<<function on_player_disconnect at 0xede00224>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	Repeat.__init__: <<function _radio_refresh at 0xede0b02c>> <()> <{}>
2021-02-09 14:08:18 - sp	-	DEBUG	Repeat.__init__: <<function _esc_refresh at 0xede0b074>> <()> <{}>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__<<function on_player_disconnect at 0xede0b14c>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientDisconnect.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	Setting up entities listener...
2021-02-09 14:08:18 - sp	-	DEBUG	Setting up versioning...
2021-02-09 14:08:18 - sp	-	DEBUG	Pre-loading libsqlite3.so.0...
2021-02-09 14:08:18 - sp	-	MESSAGE	[SP] Loading plugin 'adaptive_radar'...
2021-02-09 14:08:18 - sp	-	DEBUG	OnNetworkedEntityCreated.__init__<<function on_networked_entity_created at 0xee83b854>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnNetworkedEntityCreated.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	Hooking function: type=PRE, addr=4092132160, conv=CDECL, args=(_memory.DataType.POINTER, _memory.DataType.POINTER, _memory.DataType.INT, _memory.DataType.POINTER), rtype=VOID, callback=<function _pre_send_user_message at 0xee717bfc>
2021-02-09 14:08:18 - sp	-	MESSAGE	[SP] Successfully loaded plugin 'adaptive_radar'.
2021-02-09 14:08:18 - sp	-	MESSAGE	[SP] Loading plugin 'es_emulator'...
2021-02-09 14:08:18 - sp	-	DEBUG	OnLevelInit.__init__<<function on_level_init at 0xecf0841c>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnLevelInit.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	OnNetworkidValidated.__init__<<function on_network_id_validated at 0xecf08464>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnNetworkidValidated.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientSettingsChanged.__init__<<function on_client_settings_changed at 0xecf084ac>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientSettingsChanged.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	OnQueryCvarValueFinished.__init__<<function on_query_cvar_value_finished at 0xecf084f4>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnQueryCvarValueFinished.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	OnTick.__init__<<function on_tick at 0xecf0853c>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnTick.__init__ - Registering
2021-02-09 14:08:18 - sp	-	DEBUG	OnLevelInit._unload_instance - Unregistering <<function on_level_init at 0xecf0841c>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnNetworkidValidated._unload_instance - Unregistering <<function on_network_id_validated at 0xecf08464>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnClientSettingsChanged._unload_instance - Unregistering <<function on_client_settings_changed at 0xecf084ac>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnQueryCvarValueFinished._unload_instance - Unregistering <<function on_query_cvar_value_finished at 0xecf084f4>>
2021-02-09 14:08:18 - sp	-	DEBUG	OnTick._unload_instance - Unregistering <<function on_tick at 0xecf0853c>>
2021-02-09 14:08:18 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/plugins/command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "../addons/source-python/packages/source-python/plugins/manager.py", line 207, in load
    plugin._load()
  File "../addons/source-python/packages/source-python/plugins/instance.py", line 76, in _load
    self.module.load()
  File "../addons/source-python/plugins/es_emulator/es_emulator.py", line 42, in load
    from . import cmds
  File "../addons/source-python/plugins/es_emulator/cmds.py", line 24, in <module>
    from .logic import cfg_scripts
  File "../addons/source-python/plugins/es_emulator/logic.py", line 423, in <module>
    default_event_registration()
  File "../addons/source-python/plugins/es_emulator/logic.py", line 188, in default_event_registration
    if not register_for_event_file('../hl2/resource/gameevents.res'):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 223, in register_for_event_file
    events = KeyValues.load_from_file(file_name)

ValueError: Failed to load from file.


2021-02-09 14:08:18 - sp	-	MESSAGE	[SP] Plugin 'es_emulator' was unable to be loaded.
```

**Comment by NosferatuJoe** [comment]
```
2021-02-09 14:08:19 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)

TypeError: not enough arguments for format string


2021-02-09 14:08:19 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)

TypeError: not enough arguments for format string
```

**Comment by NosferatuJoe** [comment]
These issues were only present after the "sp update". These do not occur with @Xiazee's fix.

**Comment by Ayuto** [comment]
Duplicate: https://github.com/Ayuto/EventScripts-Emulator/issues/55
